// Node.js script to generate src/imageList.js from public/images/
const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, 'public', 'images');
const outputFile = path.join(__dirname, 'src', 'imageList.js');

const supportedExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.JPG', '.JPEG', '.PNG', '.WEBP', '.GIF'];

fs.readdir(imagesDir, (err, files) => {
  if (err) {
    console.error('Error reading images directory:', err);
    process.exit(1);
  }
  const imageFiles = files.filter(file => supportedExtensions.includes(path.extname(file)));
  const arrayString = `// Auto-generated by generateImageList.js\nconst imageList = [\n  ${imageFiles.map(f => `'${f}'`).join(',\n  ')}\n];\n\nexport default imageList;\n`;
  fs.writeFileSync(outputFile, arrayString);
  console.log(`Generated ${outputFile} with ${imageFiles.length} images.`);
});
